### ISSUE TITLE
Composition gap: in-shadow transforms (import.meta.glob; likely MDX/CSS-modules) invisible to esbuild when tsconfig paths + node_modules coexist

### ISSUE THREAD

**Issue by Takazudo** [Takazudo/zudo-front-builder#675]
## Summary

In-shadow source transforms are **invisible to esbuild when a project has BOTH a real `node_modules` AND non-empty tsconfig `compilerOptions.paths`**. Confirmed for `import.meta.glob` expansion (#665); **suspected but UNVERIFIED** for MDX and CSS-module transforms by the same mechanism.

Discovered during epic #667 (zzmod migration fixes) by the end-to-end confirm test added in #673.

## Mechanism

`materialise_shadow` writes transformed files (glob-expanded, MDX-compiled, CSS-module-rewritten) into the *shadow* tree. esbuild only reads those shadow files when invoked with `--preserve-symlinks`. But `run_esbuild` (`crates/zfb-build/src/bundler.rs`, the `--preserve-symlinks` decision block ~line 3852–3883) **omits `--preserve-symlinks` when `node_modules_dir.is_some()` AND `tsconfig_paths` is non-empty** — the pre-existing #443/#450/#553 machinery that protects workspace-package path-alias resolution.

In that config esbuild canonicalises each symlinked importer back to its **original** source path and resolves relative imports from there, so it reads the original (untransformed) file and never sees the shadow's transformed version.

## Impact

This is precisely the **zzmod styleguide-v2** config (a `pnpm install`'d `node_modules` + tsconfig `paths` + `import.meta.glob('components/**/*.stories.tsx', { eager: true })`). There, the glob silently expands to nothing → empty story registry → the original `getModuleBySlugSync is not a function` symptom that #665 was meant to fix.

So `import.meta.glob` (#665) works in isolation but **no-ops in its primary target config**. It composes fine when there are no path aliases (verified) — the gap is specifically transforms + paths + node_modules together.

## Repro

`crates/zfb-build/tests/migration_fixes_integration_confirm.rs::zzmod_all_five_migration_fixes_compose` — the test could only go green by splitting into TWO `bundle()` calls (one with `tsconfig_paths` for the alias/exclude/hardBreaks assertions, one without for the glob assertion). See its ~30-line `NOTE` block comment documenting the two-build necessity and citing the `--preserve-symlinks` branch at `bundler.rs:3868`.

## Not verified

- Whether MDX (`compile_mdx_to_jsx_module_cached`) and CSS-module (`rewrite_css_modules_in_shadow`) transforms ALSO silently break in the paths+node_modules config. The mechanism predicts they would, but no existing test exercises a transform + non-empty `tsconfig_paths` + real `node_modules` together, so this is **unconfirmed** — verify before assuming.

## Possible fix directions (need careful validation against #443/#450/#553)

1. When transforms + paths + node_modules coexist, **materialise the reachable source graph as real copies** (not symlinks) in the shadow, so esbuild canonicalisation is a no-op and it reads the transformed files. `--preserve-symlinks` stays off, so node_modules path-alias resolution is preserved.
2. Resolve the `--preserve-symlinks` vs workspace path-alias tension differently (the comment block at `bundler.rs:3835–3851` documents exactly why the current gate exists).

Either is a deep change to delicate machinery — should be a fresh, carefully-validated PR with tests covering all three transform types × {paths, no-paths} × {node_modules, none}, NOT a pre-release patch.

**Comment by Takazudo** [comment]
Fix planned + in progress as sub-issue https://github.com/Takazudo/zudo-front-builder/issues/677 (full fix: copy_mode + dual-target alias rebase), under epic #667. Closes when that merges.

**Comment by Takazudo** [comment]
Fixed by #677, merged into main via #674. **What composes now:** import.meta.glob + CSS-modules with tsconfig paths + real node_modules in a single build, for both relative imports AND `@/`-aliases into mirrored source dirs (including the common whole-root `@/* -> ./*`). Mechanism: copy_mode (copy-not-symlink in branch 4) + dual-target alias rebase (shadow-first, real-fallback); the --preserve-symlinks gate is unchanged so #443/#450 cannot regress (proven by the gate test + a new discriminator). **Residual (tracked, not a regression):** alias targets that are out-of-root (`../shared/*`), gitignored, or top-level files degrade gracefully via the real-fallback — they resolve but their in-shadow transforms are not applied (= pre-fix behaviour, never a build failure).
